version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: admin
  lethality:
    image: lethality
    restart: always
    ports:
      - "4433:4433"
    environment: 
      HOST: localhost
      DATABASE_USERNAME: mongo_user
      DATABASE_PASSWORD: mongo_secret
      MONGO_URL: mongodb://mongo_user:mongo_secret@mongo:27017
    links: 
      - mongo
    depends_on: 
      - mongo
# export MONGO_URL=mongodb://admin:admin@0.0.0.0:27017
#FLASK_APP=$PWD/app/http/api/endpoints.py FLASK_ENV=development python3 -m flask run --port=4433
